version: "3.8"
services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  web1:
    container_name: web1
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "5001:5000"
      - "9091:9090"
    environment:
      - NAME=web1
    depends_on:
      - redis

  web2:
    container_name: web2
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "5002:5000"
      - "9092:9090"
    environment:
      - NAME=web2
    depends_on:
      - redis

  web3:
    container_name: web3
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "5003:5000"
      - "9093:9090"
    environment:
      - NAME=web3
    depends_on:
      - redis

  web5:
    container_name: web5
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "5005:5000"
      - "9095:9090"
    environment:
      - NAME=web5
    depends_on:
      - redis
